### ISSUE TITLE
Add version switcher in docs

### ISSUE THREAD

**Issue by mbabker** [BabDev/babdev.com#9]
When a package has multiple versions, there should be a version switcher to let a user select the version of docs they want to view.  Might need some other minor adjustments to make it clear what version is visible as well.

- https://www.babdev.com/open-source/packages/babdevpagerfantabundle/docs/2.x/intro
- https://www.babdev.com/open-source/packages/babdevpagerfantabundle/docs/3.x/intro (not linked anywhere but I went ahead and added it to the site config since the branch is WIP)

**Comment by Sandra97** [comment]
Some ideas so that people know the documentation of which version they are looking at
![2](https://user-images.githubusercontent.com/4682328/83394143-57e40680-a3f8-11ea-86b4-dd556e3f78ac.png)
![index](https://user-images.githubusercontent.com/4682328/83394145-587c9d00-a3f8-11ea-9e91-eae7884660c4.png)

Regarding the navigation according to the version, do you intend to have 2 docs: one documentation for v2 and one for v3 (and then one for v4 and so on) or docs for minor versions too?

**Comment by mbabker** [comment]
> Some ideas so that people know the documentation of which version they are looking at

TBH, the switcher can probably double as the "what version am I on" thing too.  See https://symfony.com/doc/current/messenger.html and https://laravel.com/docs/7.x/validation as examples.  Whether there needs to be other unique identifiers somewhere else (i.e. page titles or meta descriptions) is something to figure out later, I'm just thinking of the main functionality needs right now.

> Regarding the navigation according to the version, do you intend to have 2 docs: one documentation for v2 and one for v3 (and then one for v4 and so on) or docs for minor versions too?

The docs will be based on major versions (so for the Pagerfanta bundle right now it's 2.x and 3.x, for the other stuff right now it's only 1.x but sooner or later there will be B/C breaks and a 2.x release).

**Comment by Sandra97** [comment]
Yes, these 2 examples are really good. 

Even if I prefer the look of the Laravel one, the Symfony one is (for me) more visible and more efficient (when something looks like a button, you see it immediately and you click on it, it's more eye catchy)
